services:
  - type: web
    name: mp-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build || echo "no frontend build"
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: MP_ACCESS_TOKEN
        sync: false
      - key: APP_BASE_URL
        sync: false
      - key: MP_WEBHOOK_URL
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
